import java.util.Scanner;
import java.util.Random;
class NumberGame
{
    public static void main(String args[])
    {
        Scanner sy=new Scanner(System.in);
        System.out.println("\n********Welcome to THE NUMBER GAME********\n");
        System.out.println("Take a guess of a number from 1 to 100\nA random number will be generated by the system\n");
        System.out.println("You can play many rounds you want\n");
        System.out.println("your result will be displayed at the end\n");

        int play;
        System.out.println("Enter the number of rounds you want to play:");
        play=sy.nextInt();
        int system_generated_number;
        Random random_number=new Random();
        int round=1;
        int score=0;
        int any=1;
        
        for(int i=0;i<play;i++)
        {
            int attempt_no=1;
            int start=1;
            int end=100;
            int nok=0;
            system_generated_number=random_number.nextInt(end-start+1)+start;
            for(int game=0;game<3;game++)
            {
                int user_number;
                any=system_generated_number;
                 System.out.println("Your "+attempt_no+" attempt");
                attempt_no++;

                System.out.println("Enter the number");
                int number=sy.nextInt();

                if(number>any)
                {
                    System.out.println("\nYour entered number "+number+" is high\n");
                }

                else if(number<any)
                {
                    System.out.println("\nYour entered number "+number+" is low\n");
                }
                else if(number==any)
                {
                    System.out.println("\nYIPEEEE!!!! You found the exact number \n");
                    score++;
                    break;
                }
                else{
                    System.out.println("\nYour entered number is either less than 0 or greater than 100\n");
                }

            }


            System.out.println("you have completed your "+round+" round"); round++;

        }

        System.out.println("\n***********Result is************\n");
        System.out.println("The score is "+score);
        System.out.println("\n**********Congratulations You Finished THE NUMBER GAME***************");
    }
}